#!/usr/bin/env python3

import sys

table = {
    # vim           
    'nvim':             '',
    'vim':              '',
    # shells
    'bash':             '',
    'zsh':              '',
    'fish':             '',
    'csh':              '',
    # python interpreters
    'python':           '',
    'python2.7':        '',
    'python3.7':        '',
    'Python':           '',
    'ipython':          '',
    'docker-compose':   '',
    'dev':              '',
}

print(table.get(sys.argv[1], ''))

# vim: set ft=python
